#!/bin/sh

## jpegoptim and optipng must all be installed
## if you don't have them
## 1. shame on you!!
## mac
## 2. brew install jpegoptim mozjpeg optipng
## linux
## 2. sbopkg -i jpegoptim -i mozjpeg -i optipng
## (slackware already has jpegtran, 
## although it will check for the mozjpeg version)

if [ -z $1 ]; then
  $1="90"
fi

read -p "Would you like to BACKUP the original files? [y/N]: " response
case $response in
  [yY][eE][sS]|[yY])
    export BACKUPIMAGES=true;
    echo "You are backing things up, better safe than sorry!";
    ;;
  *)
    echo "You are a risk taker.";
    ;;
esac

if [ "$BACKUPIMAGES" = true ]; then
  mkdir -pv original-image-files/
  find . -name "*.jpg" -type f -exec cp -R {} original-image-files/ \;
  find . -name "*.jpeg" -type f -exec cp -R {} original-image-files/ \;
  find . -name "*.png" -type f -exec cp -R {} original-image-files/ \;
  mv original-image-files/ ../original-image-files/
fi


if [ "$( uname -s )" = Darwin ] && [ ! -z "$( ls /usr/local/Cellar/mozjpeg/ )" ]; then
  find . -name "*.jpg" -type f -exec /usr/local/Cellar/mozjpeg/2.1/bin/jpegtran -verbose -outfile {} {} \;
  find . -name "*.jpeg" -type f -exec /usr/local/Cellar/mozjpeg/2.1/bin/jpegtran -verbose -outfile {} {} \;
elif [ ! -z "$( ls /opt/libmozjpeg/bin/ )" ]; then
  find . -name "*.jpg" -type f -exec /opt/libmozjpeg/bin/jpegtran -verbose -outfile {} {} \;
  find . -name "*.jpeg" -type f -exec /opt/libmozjpeg/bin/jpegtran -verbose -outfile {} {} \;
else
  find . -name "*.jpg" -type f -exec jpegtran -verbose -outfile {} {} \;
  find . -name "*.jpeg" -type f -exec jpegtran -verbose -outfile {} {} \;
fi

find . -name "*.jpg" -type f -exec jpegoptim -m$1 {} \;
find . -name "*.jpeg" -type f -exec jpegoptim -m$1 {} \;
find . -name "*.png" -type f -exec optipng {} \;

