#!/bin/sh

## jpegoptim and optipng must all be installed
## if you don't have them
## 1. shame on you!!
## mac
## 2. brew install jpegoptim mozjpeg optipng
## linux
## 2. sbopkg -i jpegoptim -i mozjpeg -i optipng
## (slackware already has jpegtran, 
## although it will check for the mozjpeg version)


read -p "Would you like to BACKUP the original files? [y/N]: " response
case $response in
  [yY][eE][sS]|[yY])
    export BACKUPIMAGES=true;
    echo "You are backing things up, better safe than sorry!";
    ;;
  *)
    echo "You are a risk taker.";
    ;;
esac

read -p "Would you like to remove EXIF data? [y/N]: " response
case $response in
  [yY][eE][sS]|[yY])
    export EXIFREMOVE=true;
    echo "You are removing EXIF, keep it tidy!";
    ;;
  *)
    echo "You like to know the lens used.";
    ;;
esac


if [ "$BACKUPIMAGES" = true ]; then
  mkdir -pv imgult-backup-files/
  find . -name "*.jpg" -type f -exec cp -R {} imgult-backup-files/ \;
  find . -name "*.jpeg" -type f -exec cp -R {} imgult-backup-files/ \;
  find . -name "*.png" -type f -exec cp -R {} imgult-backup-files/ \;
  mv imgult-backup-files/ ../imgult-backup-files/
fi


if [ "$EXIFREMOVE" = true ] && [ "$( uname -s )" = Darwin ] && [ ! -z "$( ls /usr/local/Cellar/mozjpeg/ )" ]; then
  find . -name "*.jpg" -type f -exec /usr/local/Cellar/mozjpeg/2.1/bin/jpegtran -verbose -copy none -outfile {} {} \;
  find . -name "*.jpeg" -type f -exec /usr/local/Cellar/mozjpeg/2.1/bin/jpegtran -verbose -copy none -outfile {} {} \;
elif [ "$( uname -s )" = Darwin ] && [ ! -z "$( ls /usr/local/Cellar/mozjpeg/ )" ]; then
  find . -name "*.jpg" -type f -exec /usr/local/Cellar/mozjpeg/2.1/bin/jpegtran -verbose -outfile {} {} \;
  find . -name "*.jpeg" -type f -exec /usr/local/Cellar/mozjpeg/2.1/bin/jpegtran -verbose -outfile {} {} \;
elif [ "$EXIFREMOVE" = true ] && [ ! -z "$( ls /opt/libmozjpeg/bin/ )" ]; then
  find . -name "*.jpg" -type f -exec /opt/libmozjpeg/bin/jpegtran -verbose -copy none -outfile {} {} \;
  find . -name "*.jpeg" -type f -exec /opt/libmozjpeg/bin/jpegtran -verbose -copy none -outfile {} {} \;
elif [ ! -z "$( ls /opt/libmozjpeg/bin/ )" ]; then
  find . -name "*.jpg" -type f -exec /opt/libmozjpeg/bin/jpegtran -verbose -outfile {} {} \;
  find . -name "*.jpeg" -type f -exec /opt/libmozjpeg/bin/jpegtran -verbose -outfile {} {} \;
elif [ "$EXIFREMOVE" = true ]; then
  find . -name "*.jpg" -type f -exec jpegtran -verbose -copy none -outfile {} {} \;
  find . -name "*.jpeg" -type f -exec jpegtran -verbose -copy none -outfile {} {} \;
else
  find . -name "*.jpg" -type f -exec jpegtran -verbose -outfile {} {} \;
  find . -name "*.jpeg" -type f -exec jpegtran -verbose -outfile {} {} \;
fi

if [ -z $1 ]; then
  find . -name "*.jpg" -type f -exec jpegoptim -m90 {} \;
  find . -name "*.jpeg" -type f -exec jpegoptim -m90 {} \;
else
  find . -name "*.jpg" -type f -exec jpegoptim -m$1 {} \;
  find . -name "*.jpeg" -type f -exec jpegoptim -m$1 {} \;
fi

if [ "$EXIFREMOVE" = true ]; then
  find . -name "*.png" -type f -exec optipng -strip all {} \;
else
  find . -name "*.png" -type f -exec optipng {} \;
fi

